version: '3.7'
services:
  proxy:
    restart: always
    build:
      context: ./src/proxy
      dockerfile: Dockerfile
    ports:
      - '9000:80'
    links:
      - web
      - api

  db:
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - db-data:/data

  api:
    tty: true
    image: node:11
    working_dir: /api
    command: /bin/bash -c 'yarn && node index.js'
    expose:
      - '8000'
    links:
      - db
    volumes:
      - ./src/api:/api:delegated

  web:
    tty: true
    image: node:11
    working_dir: /web
    command: /bin/bash -c 'yarn && node index.js'
    expose:
      - '8080'
    volumes:
      - ./src/web:/web:delegated

volumes:
  db-data:
