version: '3.7'
services:
  proxy:
    restart: always
    build:
      context: ./src/proxy
      dockerfile: Dockerfile
    ports:
      - 9000:80
    links:
      - web
      - api

  db:
    tty: true
    build: ./src/db
    command: neo4j start
    ports:
      - 7474:7474
    expose:
      - 7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - db-data:/data

  api:
    tty: true
    image: node:11
    working_dir: /api
    command: /bin/bash -c 'yarn && yarn start'
    ports:
      - 8000:8000
    links:
      - db
    volumes:
      - ./src/api:/api:delegated

  web:
    tty: true
    image: node:11
    working_dir: /web
    command: /bin/bash -c 'yarn && node index.js'
    expose:
      - 8080
    volumes:
      - ./src/web:/web:delegated

volumes:
  db-data:
